# Generated by Django 3.2.5 on 2021-08-04 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='RequestTeacher',
        ),
    ]
