# Generated by Django 3.2.5 on 2021-08-06 08:05

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_teacherprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherprofile',
            name='country',
        ),
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Other', 'Other')], default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='bio',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='facebook',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='language',
            field=models.CharField(choices=[('english', 'english'), ('french', 'french'), ('spanish', 'spanish'), ('portuguese', 'portuguese')], default='english', max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='linkedin',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='twitter',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='youtube',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
    ]
