# Generated by Django 3.2.5 on 2021-08-02 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210802_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='class_my',
            new_name='course_class',
        ),
    ]
