# Generated by Django 3.2.5 on 2021-08-02 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20210802_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
