# Generated by Django 3.2.5 on 2021-08-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='target_audience',
            field=models.CharField(choices=[('All', 'all'), ('Beginners', 'beginner'), ('Intermediate', 'intermediate'), ('Advanced', 'advanced'), ('Professional', 'professional')], default='all', max_length=40),
        ),
    ]
