# Generated by Django 3.2.5 on 2021-08-05 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20210805_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subcategory'),
        ),
    ]
