# Generated by Django 3.2.5 on 2021-08-07 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_alter_course_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competence_1', models.TextField(blank=True, null=True)),
                ('competence_2', models.TextField(blank=True, null=True)),
                ('competence_3', models.TextField(blank=True, null=True)),
                ('competence_4', models.TextField(blank=True, null=True)),
                ('competence_5', models.TextField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
