# Generated by Django 3.2.5 on 2021-08-07 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_auto_20210807_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='apply_discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
