# Generated by Django 3.2.5 on 2021-08-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_course_apply_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='apply_discount',
            field=models.FloatField(default=0),
        ),
    ]
