# Generated by Django 3.2.5 on 2021-08-05 15:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartcourse',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
