# Generated by Django 3.2.5 on 2021-08-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartcourse_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartcourse',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
