# Generated by Django 3.2.5 on 2021-08-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favourite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='date',
            new_name='date_created',
        ),
    ]
